/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianQuest
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  party: {
    hero: {
      id: "hero",
      name: "\u52C7\u8005",
      level: 1,
      currentXp: 0,
      nextLevelXp: 100,
      imageSeed: "Mochi"
      // Cuter seed
    },
    playboy: {
      id: "playboy",
      name: "\u904A\u3073\u4EBA",
      level: 1,
      currentXp: 0,
      nextLevelXp: 100,
      imageSeed: "Coco"
      // Cuter seed
    },
    scholar: {
      id: "scholar",
      name: "\u8CE2\u8005",
      level: 1,
      currentXp: 0,
      nextLevelXp: 100,
      imageSeed: "Vanilla"
      // Cuter seed
    },
    hunter: {
      id: "hunter",
      name: "\u72E9\u4EBA",
      level: 1,
      currentXp: 0,
      nextLevelXp: 100,
      imageSeed: "Choco"
      // Cuter seed
    }
  },
  wanderingInterval: 5,
  wanderingDistance: 0
};
var StatusModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const party = this.plugin.settings.party;
    contentEl.createEl("h2", { text: "\u2694\uFE0F \u5192\u967A\u306E\u8A18\u9332" });
    const container = contentEl.createDiv({ cls: "quest-status-container" });
    Object.values(party).forEach((char) => {
      this.createCharacterCard(container, char);
    });
  }
  createCharacterCard(container, char) {
    const card = container.createDiv({ cls: "quest-char-card" });
    let imgUrl = `https://api.dicebear.com/9.x/pixel-art/svg?seed=${char.imageSeed}`;
    if (char.customImage) {
      imgUrl = char.customImage;
    }
    card.createEl("img", {
      attr: { src: imgUrl },
      cls: "quest-char-img"
    });
    const info = card.createDiv({ cls: "quest-char-info" });
    info.createEl("h3", { text: `${char.name} (Lv.${char.level})` });
    info.createDiv({ text: `XP: ${char.currentXp} / ${char.nextLevelXp}` });
    const barBg = info.createDiv({ cls: "quest-xp-bar-bg" });
    const progress = char.currentXp / char.nextLevelXp * 100;
    barBg.createDiv({
      cls: "quest-xp-bar-fill",
      attr: { style: `width: ${progress}%` }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ObsidianQuest = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lastLength = 0;
    this.lastLinkCount = 0;
    this.lastTaskCount = 0;
  }
  async onload() {
    await this.loadSettings();
    this.wanderingParty = new WanderingParty(this);
    this.wanderingParty.load();
    this.addSettingTab(new ObsidianQuestSettingTab(this.app, this));
    this.addRibbonIcon("sword", "\u5192\u967A\u306E\u30B9\u30C6\u30FC\u30BF\u30B9\u3092\u958B\u304F", (evt) => {
      new StatusModal(this.app, this).open();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian.MarkdownView) {
          this.updateCurrentStats(leaf.view.editor);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "editor-change",
        (editor, view) => {
          this.handleEditorChange(editor);
        }
      )
    );
  }
  onunload() {
    if (this.wanderingParty) {
      this.wanderingParty.unload();
    }
  }
  updateCurrentStats(editor) {
    const text = editor.getValue();
    this.lastLength = text.length;
    this.lastLinkCount = (text.match(/\[\[.*?\]\]/g) || []).length;
    this.lastTaskCount = (text.match(/- \[x\]/g) || []).length;
  }
  async handleEditorChange(editor) {
    const text = editor.getValue();
    const currentLength = text.length;
    const currentLinkCount = (text.match(/\[\[.*?\]\]/g) || []).length;
    const currentTaskCount = (text.match(/- \[x\]/g) || []).length;
    const lengthDiff = currentLength - this.lastLength;
    const linkDiff = currentLinkCount - this.lastLinkCount;
    const taskDiff = currentTaskCount - this.lastTaskCount;
    if (lengthDiff > 0) {
      if (lengthDiff === 1) {
        this.gainXp("hero", 1);
      } else {
        this.gainXp("playboy", lengthDiff);
      }
    }
    if (linkDiff > 0) {
      this.gainXp("scholar", linkDiff * 10);
      new import_obsidian.Notice(`\u{1F4D6} \u8CE2\u8005\u304C\u77E5\u8B58\u3092\u7E4B\u3052\u305F\uFF01 (+${linkDiff * 10} XP)`);
    }
    if (taskDiff > 0) {
      this.gainXp("hunter", taskDiff * 20);
      new import_obsidian.Notice(`\u{1F3F9} \u72E9\u4EBA\u304C\u30BF\u30B9\u30AF\u3092\u4ED5\u7559\u3081\u305F\uFF01 (+${taskDiff * 20} XP)`);
    }
    this.lastLength = currentLength;
    this.lastLinkCount = currentLinkCount;
    this.lastTaskCount = currentTaskCount;
  }
  async gainXp(charKey, amount) {
    const char = this.settings.party[charKey];
    char.currentXp += amount;
    if (char.currentXp >= char.nextLevelXp) {
      char.level += 1;
      char.currentXp = char.currentXp - char.nextLevelXp;
      char.nextLevelXp = Math.floor(char.nextLevelXp * 1.5);
      new import_obsidian.Notice(`\u{1F389} ${char.name}\u304C\u30EC\u30D9\u30EB\u30A2\u30C3\u30D7\uFF01 Lv.${char.level}\uFF01`);
    }
    await this.saveSettings();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var WanderingParty = class {
  constructor(plugin) {
    this.elements = [];
    this.intervalId = null;
    this.isDragging = false;
    this.draggedEl = null;
    this.offsetX = 0;
    this.offsetY = 0;
    // --- Interaction Handlers ---
    this.onMouseDown = (e, el) => {
      e.preventDefault();
      this.isDragging = true;
      this.draggedEl = el;
      const rect = el.getBoundingClientRect();
      this.offsetX = e.clientX - rect.left;
      this.offsetY = e.clientY - rect.top;
      el.style.transition = "none";
    };
    this.onMouseMove = (e) => {
      if (!this.isDragging || !this.draggedEl)
        return;
      e.preventDefault();
      const x = e.clientX - this.offsetX;
      const y = e.clientY - this.offsetY;
      this.draggedEl.style.left = `${x}px`;
      this.draggedEl.style.top = `${y}px`;
    };
    this.onMouseUp = () => {
      if (this.isDragging && this.draggedEl) {
        this.draggedEl.style.transition = "top 3s ease-in-out, left 3s ease-in-out";
      }
      this.isDragging = false;
      this.draggedEl = null;
    };
    this.onClick = (e, el, char) => {
      if (this.isDragging)
        return;
      el.removeClass("quest-jump");
      void el.offsetWidth;
      el.addClass("quest-jump");
      new import_obsidian.Notice(`${char.name}: "\u5192\u967A\u306F\u9806\u8ABF\uFF1F"`);
    };
    this.plugin = plugin;
  }
  load() {
    const party = this.plugin.settings.party;
    Object.values(party).forEach((char) => {
      this.createWanderer(char);
    });
    this.startInterval();
    this.moveWanderers();
    window.addEventListener("mousemove", this.onMouseMove);
    window.addEventListener("mouseup", this.onMouseUp);
  }
  unload() {
    this.stopInterval();
    this.elements.forEach((el) => el.remove());
    this.elements = [];
    window.removeEventListener("mousemove", this.onMouseMove);
    window.removeEventListener("mouseup", this.onMouseUp);
  }
  reload() {
    this.stopInterval();
    this.startInterval();
  }
  startInterval() {
    const intervalSec = this.plugin.settings.wanderingInterval || 5;
    this.intervalId = window.setInterval(() => {
      if (!this.isDragging) {
        this.moveWanderers();
      }
    }, intervalSec * 1e3);
  }
  stopInterval() {
    if (this.intervalId) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
    }
  }
  createWanderer(char) {
    let imgUrl = `https://api.dicebear.com/9.x/pixel-art/svg?seed=${char.imageSeed}`;
    if (char.customImage) {
      imgUrl = char.customImage;
    }
    const img = document.body.createEl("img", {
      cls: "quest-wanderer",
      attr: { src: imgUrl }
    });
    img.style.top = "-100px";
    img.style.left = "-100px";
    img.addEventListener("mousedown", (e) => this.onMouseDown(e, img));
    img.addEventListener("click", (e) => this.onClick(e, img, char));
    this.elements.push(img);
  }
  moveWanderers() {
    const maxDist = this.plugin.settings.wanderingDistance;
    this.elements.forEach((el) => {
      if (el === this.draggedEl)
        return;
      let x, y;
      if (maxDist > 0) {
        const rect = el.getBoundingClientRect();
        const currentX = rect.left;
        const currentY = rect.top;
        const dx = (Math.random() - 0.5) * 2 * maxDist;
        const dy = (Math.random() - 0.5) * 2 * maxDist;
        x = Math.max(0, Math.min(window.innerWidth - 60, currentX + dx));
        y = Math.max(0, Math.min(window.innerHeight - 60, currentY + dy));
      } else {
        x = Math.random() * (window.innerWidth - 60);
        y = Math.random() * (window.innerHeight - 60);
      }
      el.style.left = `${x}px`;
      el.style.top = `${y}px`;
      if (Math.random() > 0.5) {
        el.style.transform = "scaleX(-1)";
      } else {
        el.style.transform = "scaleX(1)";
      }
    });
  }
};
var ObsidianQuestSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Quest Settings" });
    new import_obsidian.Setting(containerEl).setName("Wandering Interval (seconds)").setDesc("How often the party moves around the screen.").addText((text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.wanderingInterval)).onChange(async (value) => {
      const num = Number(value);
      if (!isNaN(num) && num > 0) {
        this.plugin.settings.wanderingInterval = num;
        await this.plugin.saveSettings();
        this.plugin.wanderingParty.reload();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Wandering Distance (pixels)").setDesc("Max distance for each move. Set 0 for random screen-wide movement.").addText((text) => text.setPlaceholder("0").setValue(String(this.plugin.settings.wanderingDistance)).onChange(async (value) => {
      const num = Number(value);
      if (!isNaN(num) && num >= 0) {
        this.plugin.settings.wanderingDistance = num;
        await this.plugin.saveSettings();
      }
    }));
  }
};
